### ISSUE TITLE
Datalib not found

### ISSUE THREAD

**Issue by 1kasper** [octacian/digicompute#1]
>depends

>datalib

>https://git.endev.xyz/octacian/datalib/src/v0.1/README.md?lang=ru-RU

>404

WTF?

**Comment by octacian** [comment]
Sorry, my personal Git service is currently down. Moved to GitHub. Download master [here](https://github.com/octacian/datalib/archive/master.zip). Install the mod after renaming extracted folder to "datalib" and you'll be good to go.

**Comment by 1kasper** [comment]
Thanks.
