### ISSUE TITLE
Modules not loading on Windows

### ISSUE THREAD

**Issue by Sirvoid** [octacian/digicompute#2]
I redownloaded the mod and now it is not loading ...
http://puu.sh/tIoNA/fd7f967e14.png

I don't have any problems with any other mods ...

I never downloaded lua on my computer ??? does I need to download it for this mod ???
I'm on Windows.

**Comment by octacian** [comment]
This is really weird. With the exact same version on Linux, it works fine for me. I understand that you are using Minetest 0.4.15? Also, try typing `lua -v` in the command prompt anyway. If it is not there, download and install Lua 5.2 and then confirm with `lua -v`. I'm not quite sure how you get Lua on Windows, but there's some good information for getting started [here](https://www.lua.org/start.html).

**Comment by Sirvoid** [comment]
It seem to be a mess to install lua on Windows 
how I am actually running the others mods If I don't have it ??? that's weird
I never had that problem before

**Comment by octacian** [comment]
I will see if I can have Jordach (I believe he also runs Windows) test this as well. It is quite likely that the problem is somewhere else aside from the actual Lua version.

Could you try running `lua -v` anyways?

**Comment by garywhite207** [comment]
I'll try it & see what happens

**Comment by Sirvoid** [comment]
lua -v is not recognized as an internal or external command

**Comment by octacian** [comment]
@Sirvoid I'll have to look into what version is packaged with Minetest later.

@garywhite207 thanks. I'd really appreciate that. If there's a crash, try and post the debug log and what you did to create the crash.

**Comment by octacian** [comment]
Fixed. Original issue (attempt to index nil value, code) still unsolved.

6cdabc29348c8bd6d746c3020f887e073f4b91f1

**Comment by octacian** [comment]
Original issue (attempt to index `nil` value, `code`) solved.

a32178ae555b66034f765aa655807f3f3cf029e8
