### ISSUE TITLE
Name of this repository is a mistake or deliberately?

### ISSUE THREAD

**Issue by farooqkz** [octacian/digicompute#4]
Hi!
Its name is "digicompute" not "digicompute**r**", it's a mistake or your own choice?

**Comment by octacian** [comment]
Nope, it's supposed to be digicompute. I named it this way with digilines as an inspiration and chose to drop the **r** in "computer" as I had initially planned to not only introduce computers with this mod but also many other computer-related devices.

Anyways, hope that answers your question. Will close this issue for now.
